apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: roboshop
  labels:
    name: debug
    project: roboshop
spec:
  imagePullSecrets:
    - name: dockerhub-secret   
  containers:
    - name: debug
      image: anilkathoju/debug:v1
      imagePullPolicy: Always
