apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: roboshop
  labels:
    name: debug
    project: roboshop
spec:
  containers:
  - name: debug
    image: anilkathoju/debug:v1
    imagePullPolicy: Always
    imagePullSecrets:
    - name: dockerhub-secret