apiVersion: apps/v1
kind: Deployment
metadata:
   name: mongodb
   namespace: roboshop
   labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
   replicas: 1
   selector:
     matchLabels: #labels are used to select pods
      project: roboshop
      component: mongodb
      tier: db 
      #pod definition
   template:
     metadata: 
       labels:
          project: roboshop
          component: mongodb
          tier: db 
     spec:
       containers:
        - name: mongodb
          image: anilkathoju/mongodb:v1
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
             tcpSocket:
              port: 27017
             initialDelaySeconds: 15
             periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
   name : mongodb
   namespace: roboshop
spec:
  selector:
    project: roboshop
    component: mongodb
    tier: db
  ports:
    - protocol: TCP
      port: 27017  # servcie port
      targetPort: 27017 # container
        