apiVersion: apps/v1
kind: Deployment
metadata:
   name: mongodb
   namespace: roboshop
   labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
   replicas: 1
   selectors:
     matchLabels: #labels are used to select pods
      project: roboshop
      component: mongodb
      tier: db 
      #pod definition
   template:
     metadata: 
       labels:
          project: roboshop
          component: mongodb
          tier: db 
     spec:
       containers:
        - name: mongodb
          image: anilkathoju/mongodb:v1

