apiVersion: apps/v1
kind: Deployment
metadata:
   name: mysql
   namespace: roboshop
   labels:
    project: roboshop
    component: mysql
    tier: db
spec:
   replicas: 1
   selector:
     matchLabels: #labels are used to select pods
      project: roboshop
      component: mysql
      tier: db 
      #pod definition
   template:
     metadata: 
       labels:
          project: roboshop
          component: mysql
          tier: db 
     spec:
       containers:
        - name: mysql
          image: anilkathoju/mysql:v1
          imagePullPolicy: Always
          resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits: 
            memory: "1Gi"
            cpu: "500m"
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
             tcpSocket:
              port: 3306
             initialDelaySeconds: 30
             periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
   name : mysql
   namespace: roboshop
spec:
  selector:
    project: roboshop
    component: mysql
    tier: db
  ports:
    - protocol: TCP
      port: 3306  # servcie port
      targetPort: 3306 # container
        